const mongoose = require('mongoose');

const appDataSchema = new mongoose.Schema({
    packageName: { type: String, required: true },
    splashTime: { type: Number, required: true },
    maxVer: { type: Number, required: true },
    adEnabled: { type: Boolean, required: true },
    alEnabled: { type: Boolean, required: true },
    forcedInt: { type: Boolean, required: true },
    adPref: { type: String, required: true },
    adFirstServe: { type: String, required: true },
    adRoundRobin: { type: Boolean, required: true },
    nativePreload: { type: Boolean, required: true },
    nativeAdPref: { type: String, required: true },
    nativeFirstServe: { type: String, required: true },
    nativeRoundRobin: { type: Boolean, required: true },
    showFbRectBanner: { type: Boolean, required: true },
    bannerAdPref: { type: String, required: true },
    bannerFirstServe: { type: String, required: true },
    bannerRoundRobin: { type: Boolean, required: true },
    inHouseEnabled: { type: Boolean, required: true },
    iapEnabled: { type: Boolean, required: true },
    appOpenEnabled: { type: Boolean, required: true },
    splashAppOpenEnabled: { type: Boolean, required: true },
    backPressEnabled: { type: Boolean, required: true },
    rewardVideoEnabled: { type: Boolean, required: true },
    rewardIntEnabled: { type: Boolean, required: true },
    intType: { type: String, required: true },
    intSkip: { type: Number, required: true },
    intClickInterval: { type: Number, required: true },
    intTimeInterval: { type: Number, required: true },
    intRandom: { type: Boolean, required: true },
    nativeRandom: { type: Boolean, required: true },
    smallNativeRandom: { type: Boolean, required: true },
    bannerRandom: { type: Boolean, required: true },
    appOpenBackFill: { type: Boolean, required: true },
    intBackFill: { type: Boolean, required: true },
    nativeBackFill: { type: Boolean, required: true },
    smallNativeBackFill: { type: Boolean, required: true },
    bannerBackFill: { type: Boolean, required: true },
    rewardVideoBackFill: { type: Boolean, required: true },
    rewardIntBackFill: { type: Boolean, required: true },
    adBtnBGColor: { type: String, required: true },
    adBtnTxtColor: { type: String, required: true },
    ppLink: { type: String, required: true },
    feedBackId: { type: String, required: true },
    appOpenId: { type: String, required: true },
    appOpenIds: [{ type: String }],
    intIds: [{ type: String }],
    nativeIds: [{ type: String }],
    smallNativeIds: [{ type: String }],
    bannerIds: [{ type: String }],
    rewardIntIds: [{ type: String }],
    rewardVideoIds: [{ type: String }],
    alAppOpen: { type: String, required: true },
    alInt: { type: String, required: true },
    alNative: { type: String, required: true },
    alSmallNative: { type: String, required: true },
    alBanner: { type: String, required: true },
    alRewardVideo: { type: String, required: true },
    fbInt: { type: String, required: true },
    fbNative: { type: String, required: true },
    fbBanner: { type: String, required: true },
    fbNativeBanner: { type: String, required: true },
    fbRectBanner: { type: String, required: true },
    fbRewardInt: { type: String, required: true },
    intScreensCount: { type: String, required: true },
    intSkips: { type: String, required: true },
    intScreens: { type: String, required: true },
    nativeScreens: { type: String, required: true },
    smallNativeScreens: { type: String, required: true },
    bannerScreens: { type: String, required: true },
    cBannerScreens: { type: String, required: true },
    inlineBannerScreens: { type: String, required: true },
    rewardIntScreens: { type: String, required: true },
    rewardVideoScreens: { type: String, required: true }
});

module.exports = mongoose.model('appAdsData', appDataSchema);